name: Deployment On K8s Cluster

on: 
  push: 
     branches: ['main']
  pull_request:
     branches: ['main']        

jobs:
  Deploy_On_Cluster:
    name: Deploy Application On Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   

      - name: Generate unique image  tag
        id: new_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_SHA::8})" 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  #  Here the . represents the root directory of the repository where the workflow is running. We can change this value if your Dockerfile is located in a different directory.
          push: true
          tags: bhasmeht/angular-image:1.1.9    # :${{ steps.new_tag.outputs.tag }}
      - name: Send Email Notification on Success
        if: success()  # Condition to check if the previous step was successful
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: bhaskarmehta422@gmail.com
          subject: 'Docker image upload successful'
          to: 'bhaskarmehta12@gmail.com, bhaskarmehta22@gmail.com'
          body: 'The Docker image was successfully uploaded to DockerHub.'

      - name: Send Email Notification on Failure
        if: failure()  # Condition to check if the previous step failed
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.your-email-provider.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: bhaskarmehta422@gmail.com
          subject: 'Docker image upload failed'
          to: 'bhaskarmehta12@gmail.com, bhaskarmehta22@gmail.com'
          body: 'There was a failure while uploading the Docker image to DockerHub. Please check the workflow logs.'         


      # - name: Install AWS CLI
      #   run: 
      #    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #    apt install unzip
      #    unzip awscliv2.zip
      #    sudo ./aws/install    

      # - name: Install Kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'v1.24.11' # default is latest stable
      #   id: install

      # - name: Install
      #   run:  |
      #       curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.11/2023-03-17/bin/linux/amd64/kubectl
      #       chmod +x ./kubectl
      #       mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      #       kubectl version --client  

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1

      # - name: Update Kube Configure
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
      #     aws eks update-kubeconfig --region ap-south-1 --name mycluster
 

      # - name: Deploy to EKS
      #   run: kubectl apply -f Deployments/      


